"""initial migration

Revision ID: 0292aac4f94b
Revises: 
Create Date: 2023-01-06 20:16:53.944534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0292aac4f94b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('spots_trigger', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('location', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('location_game_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'games', ['location_game_id'], ['id'])

    # with op.batch_alter_table('games', schema=None) as batch_op:
        #batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        # batch_op.add_column(sa.Column('owner_id', sa.String(), nullable=True))
        # batch_op.add_column(sa.Column('time', sa.String(), nullable=True))
        # batch_op.add_column(sa.Column('location', sa.String(), nullable=True))
        # batch_op.add_column(sa.Column('location_id', sa.String(), nullable=True))
        # batch_op.add_column(sa.Column('location_type_id', sa.String(), nullable=True))
        # batch_op.add_column(sa.Column('location_slug', sa.String(), nullable=True))
        # batch_op.add_column(sa.Column('hood', sa.String(), nullable=True))
        # batch_op.add_column(sa.Column('skillRange', sa.String(), nullable=True))
        # batch_op.add_column(sa.Column('type', sa.String(), nullable=True))
        # batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        # batch_op.add_column(sa.Column('statusName', sa.String(), nullable=True))
        # batch_op.add_column(sa.Column('spotsOpen', sa.String(), nullable=True))
        # batch_op.add_column(sa.Column('price', sa.String(), nullable=True))
        # batch_op.add_column(sa.Column('market_id', sa.String(), nullable=True))
        # batch_op.add_column(sa.Column('reservation_id', sa.String(), nullable=True))
        # batch_op.add_column(sa.Column('date', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('date')
        batch_op.drop_column('reservation_id')
        batch_op.drop_column('market_id')
        batch_op.drop_column('price')
        batch_op.drop_column('spotsOpen')
        batch_op.drop_column('statusName')
        batch_op.drop_column('name')
        batch_op.drop_column('type')
        batch_op.drop_column('skillRange')
        batch_op.drop_column('hood')
        batch_op.drop_column('location_slug')
        batch_op.drop_column('location_type_id')
        batch_op.drop_column('location_id')
        batch_op.drop_column('location')
        batch_op.drop_column('time')
        batch_op.drop_column('owner_id')
        batch_op.drop_column('id')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('location_game_id')
        batch_op.drop_column('location')
        batch_op.drop_column('spots_trigger')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('name')
        batch_op.drop_column('user_id')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
