"""auto-increment appointment id

Revision ID: 204931d2ece6
Revises: 0292aac4f94b
Create Date: 2023-01-06 20:34:16.106035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '204931d2ece6'
down_revision = '0292aac4f94b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index('appointments_id_idx')

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('location_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('location_type_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('spotsopen',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('market_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('market_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.String(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('spotsopen',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('location_type_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('location_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index('appointments_id_idx', ['id'], unique=False)

    # ### end Alembic commands ###
