"""Adding column locations.

Revision ID: 6ecc439958fa
Revises: 2b7a8d977294
Create Date: 2023-01-02 13:45:42.008296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ecc439958fa'
down_revision = '2b7a8d977294'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    op.add_column('appointments', sa.Column('location', sa.String(length=255)))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'location')
    op.create_table('games',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('time', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('location', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('location_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('location_type_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('location_slug', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hood', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('skillrange', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('statusname', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('spotsopen', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('price', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('market_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('reservation_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date', sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
