"""Fixing schema

Revision ID: 721be86624c8
Revises: 42cb8a2f4789
Create Date: 2023-01-05 12:25:02.153406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '721be86624c8'
down_revision = '42cb8a2f4789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('games', sa.Column('spots_open', sa.String(), nullable=True))
    op.add_column('games', sa.Column('time', sa.String(), nullable=True))
    op.alter_column('appointments', sa.Column('user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'time')
    op.drop_column('games', 'spots_open')
    op.alter_column('appointments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
