"""Adding location to appointment

Revision ID: d61cadc7c125
Revises: 721be86624c8
Create Date: 2023-01-05 18:44:10.159306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd61cadc7c125'
down_revision = '721be86624c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('location', sa.String(length=50), nullable=True))
    op.alter_column('appointments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('appointments', 'location')
    # ### end Alembic commands ###
